/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconPark:avatar': typeof import('~icons/icon-park/avatar')['default']
    'IconParkOutline:arrowCircleLeft': typeof import('~icons/icon-park-outline/arrow-circle-left')['default']
    'IconParkOutline:check': typeof import('~icons/icon-park-outline/check')['default']
    'IconParkOutline:clear': typeof import('~icons/icon-park-outline/clear')['default']
    'IconParkOutline:delete': typeof import('~icons/icon-park-outline/delete')['default']
    'IconParkOutline:edit': typeof import('~icons/icon-park-outline/edit')['default']
    'IconParkOutline:export': typeof import('~icons/icon-park-outline/export')['default']
    'IconParkOutline:messageOne': typeof import('~icons/icon-park-outline/message-one')['default']
    'IconParkOutline:moreOne': typeof import('~icons/icon-park-outline/more-one')['default']
    'IconParkOutline:plus': typeof import('~icons/icon-park-outline/plus')['default']
    'IconParkOutline:search': typeof import('~icons/icon-park-outline/search')['default']
    'IconParkOutline:send': typeof import('~icons/icon-park-outline/send')['default']
    ImageIcon: typeof import('./../shared/components/image-icon.vue')['default']
    ImagePreview: typeof import('./../shared/components/image-preview.vue')['default']
    MediaGallery: typeof import('./../shared/components/media-gallery.vue')['default']
    MediaGalleryItem: typeof import('./../shared/components/media-gallery-item.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PageContainer: typeof import('./../shared/components/page-container.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepContainer: typeof import('./../shared/components/step-container.vue')['default']
    StepItem: typeof import('./../shared/components/step-item.vue')['default']
    SvgIcon: typeof import('./../shared/components/svg-icon.vue')['default']
    UploadContainer: typeof import('./../shared/components/upload-container.vue')['default']
    UploadProgress: typeof import('./../shared/components/upload-progress.vue')['default']
    VideoPreview: typeof import('./../shared/components/video-preview.vue')['default']
  }
}
